version: 0.1.{build}
skip_branch_with_pr: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(FULL_VERSION)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(FULL_VERSION)
environment:
  FULL_VERSION: $(APPVEYOR_BUILD_VERSION)-alpha
build_script:
- ps: >-
    & dotnet build LH.CommandLine.sln -c "Release"
    & dotnet pack src\LH.CommandLine -c "Release" /p:PackageVersion=$env:FULL_VERSION --no-build --no-restore
test_script:
- ps: >-
    & dotnet test tests\LH.CommandLine.UnitTests -c "Release"
artifacts:
- path: '**\*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: mtQQf7BN2hkg6XKLxXchbXT5FFdCIEdWwMVxIRzemgTAAe8MKq1sZS89VOf3cEGt
  skip_symbols: false
  on:
    branch: master