version: 0.1.{build}
image: Visual Studio 2017
skip_branch_with_pr: true
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(FULL_VERSION)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(FULL_VERSION)
environment:
  FULL_VERSION: $(APPVEYOR_BUILD_VERSION)-alpha
  CONFIGURATION: Release
  CODECOV_TOKEN:
    secure: 4MD/Ln1SJkDA5CbnfQo3ltc1GcL4+WpdKyXj0dD9fi6VcJQ8a6Gih66kHsiYsbKT
before_build:
- choco install codecov
build_script:
- ps: . dotnet build LH.CommandLine.sln -c $env:CONFIGURATION
- ps: . dotnet pack src\LH.CommandLine -c $env:CONFIGURATION /p:PackageVersion=$env:FULL_VERSION --no-build --no-restore
test_script:
- dotnet test ./tests/LH.CommandLine.UnitTests/LH.CommandLine.UnitTests.csproj --no-build -c $env:CONFIGURATION /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./Coverage.xml /p:Exclude="[*Tests?]*"
- codecov -f ./tests/LH.CommandLine.UnitTests/Coverage.xml -t $(CODECOV_TOKEN)
artifacts:
- path: '**\*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: mtQQf7BN2hkg6XKLxXchbXT5FFdCIEdWwMVxIRzemgTAAe8MKq1sZS89VOf3cEGt
  skip_symbols: false
  on:
    branch: master