version: 0.1.{build}
skip_branch_with_pr: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(FULL_VERSION)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(FULL_VERSION)
environment:
  FULL_VERSION: $(APPVEYOR_BUILD_VERSION)-alpha
  CODECOV_TOKEN:
    secure: 4MD/Ln1SJkDA5CbnfQo3ltc1GcL4+WpdKyXj0dD9fi6VcJQ8a6Gih66kHsiYsbKT
before_build:
- choco install opencover.portable
- choco install codecov
build_script:
- ps: >-
    & dotnet build LH.CommandLine.sln -c "Release"
    & dotnet pack src\LH.CommandLine -c "Release" /p:PackageVersion=$env:FULL_VERSION --no-build --no-restore
test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full tests\LH.CommandLine.UnitTests\LH.CommandLine.UnitTests.csproj" -filter:"+[LH.CommandLine*]* -[LH.CommandLine.UnitTests*]*" -output:".\LH.CommandLine.UnitTests.xml"
- codecov -f .\valit_coverage.xml -t $(CODECOV_TOKEN)
artifacts:
- path: '**\*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: mtQQf7BN2hkg6XKLxXchbXT5FFdCIEdWwMVxIRzemgTAAe8MKq1sZS89VOf3cEGt
  skip_symbols: false
  on:
    branch: master